### ISSUE TITLE
Rails preview mailers are broken

### ISSUE THREAD

**Issue by DanielePalombo** [solidusio-contrib/solidus_affirm#10]
### Steps to reproduce
Add this extension and visit `rails/mailers`

### Expected behavior
A list of available previews should be shown

### Actual behavior
It raises the error:

```
No route matches {:action=>"preview", :controller=>"rails/mailers", :path=>"spree/mailer_previews/carton"}
```

### System configuration
v1.4...v2.4

**Comment by alepore** [comment]
@DanielePalombo this is now fixed, right?

**Comment by DanielePalombo** [comment]
right!
